version: '3'

name: portfolio-sveltekit
services:
  cli:
    build:
      context: ./
      target: builder
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    command: sh
    networks:
      - portfolio

  dev:
    build:
      context: ./
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    networks:
      - portfolio

  prod:
    build:
      context: ./
      target: prod
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - portfolio

  nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - prod
      - certbot
    networks:
      - portfolio

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - ./.env
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    networks:
      - portfolio

networks:
  portfolio: